# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGUCS3uggskdlfhtiRQWGyR-3Hc5mpJz
"""

from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "traffic1.jpg"), output_image_path=os.path.join(execution_path , "traffic1new.jpg"))

for eachObject in detections:
  print(eachObject["name"] , " : " , eachObject["percentage_probability"] )

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

from IPython.display import Image
Image(filename='image.jpg')

from IPython.display import Image
Image(filename='imagenew.jpg')

from IPython.display import Image
Image(filename='traffic1new.jpg')

!pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl